syntax = "Lua51"

# Can't believe they didn't inherit these from .editorconfig...
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2

quote_style = "AutoPreferSingle"
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Never"
